import {
  AddressInfo,
  CardCatelog,
  CardSocialMediaLink,
  CardTestimony,
  SharedWith,
} from "./card.protocol";

export const cardDefaultData = {
  cardType: "personal" as "personal" | "business" | "organizational",
  creatorId: null,
  ownerId: null,
  cardStyle: {
    fontSize: "18px",
    fontStyle: "normal" as "normal" | "italic" | "oblique",
    fontWeight: "normal" as "normal" | "bold" | "bolder" | "lighter" | number,
    textAlign: "left" as "left" | "center" | "right" | "justify",
    textColor: "#000000",
    borderStyle: "none" as "none" | "solid" | "dashed" | "dotted" | "double",
    borderColor: "#000000",
    borderWidth: "0px",
    borderRadius: "0px",
    padding: "10px",
    margin: "15px",
    orientation: "horizontal" as "horizontal" | "vertical",
    alignment: "leading" as "leading" | "center" | "trailing",
    boxShadow: "none",
    primaryColor: "#FFFFFF",
    secondaryColor: "#000000",
  },
  organizationInfo: {
    organizationId: null,
    organizationName: "",
  },
  contactInfo: {
    email: "",
    emailType: [],
    phone: "",
    website: "",
    addresses: [] as AddressInfo[],
  },
  socialMediaLinks: [] as CardSocialMediaLink[],
  addressInfo: {
    latitude: 0,
    longitude: 0,
    country: "",
    state: "",
    city: "",
    label: "",
    street: "",
  },
  cardName: "",
  prefix: "",
  suffix: "",
  pronun: "",
  firstName: "",
  otherName: "",
  lastName: "",
  designation: "",
  socials: {} as Record<string, string>,
  testimonials: [] as CardTestimony[],
  sharedWith: [] as SharedWith[],
  catelogue: [] as CardCatelog[],
  videoUrl: "",
  cardPictureUrl: "",
  cardCoverUrl: "",
  active: true,
  createdAt: new Date(),
  updatedAt: new Date(),
};
